foreground         #c2c2c2
background         #0c0b0c
background_opacity 1.0
cursor             #c2c2c2

active_tab_foreground     #0c0b0c
active_tab_background     #c2c2c2
inactive_tab_foreground   #c2c2c2
inactive_tab_background   #0c0b0c

active_border_color   #c2c2c2
inactive_border_color #0c0b0c
bell_border_color     #4b3f3c

color0       #0c0b0c
color8       #6a566a
color1       #4b3f3c
color9       #655451
color2       #772d25
color10      #9F3D32
color3       #774942
color11      #9F6259
color4       #9f4e41
color12      #D46857
color5       #876d54
color13      #B49271
color6       #a5744e
color14      #DC9B69
color7       #968b8b
color15      #c2c2c2
